
Loading and preprocessing the data

Load the data:

echo = TRUE
setwd("/Users/fisoflo/ReprRes_Ass1")
activity <- NULL
activity <- read.csv("activity.csv", header = T, sep = ",")
The variable created during by this code are set to NULL.

echo = TRUE
df_summary <- NULL
su2 <- NULL
su <- NULL
mn_int <- NULL
activity2 <- NULL
mean_su2 <- NULL
median_su2 <- NULL
activity2_weekend <- NULL
activity2_weekday <- NULL
mean_activity2_weekday <- NULL
mean_activity2_weekend <- NULL

What is mean total number of steps taken per day?

echo = TRUE
su <- tapply(activity$steps, activity$date, sum, na.rm=T)
echo = TRUE
hist(su, xlab = "sum of steps per day", main = "histogram of steps per day")

echo = TRUE
mean_su <- round(mean(su))
median_su <- round(median(su))

print(c("The mean is",mean_su))
## [1] "The mean is" "9354"
print(c("The median is",median_su))
## [1] "The median is" "10395"

what is the average daily activity pattern ?

echo = TRUE
mn_int[which.max(mn_int)]
##   835 
## 206.2
Imputing missing values

Note that there are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data.

First, in order to visualize in which variable the NAs are:

echo = TRUE
table(is.na(activity) == TRUE)
## 
## FALSE  TRUE 
## 50400  2304
summary(activity)
##      steps               date          interval   
##  Min.   :  0.0   2012-10-01:  288   Min.   :   0  
##  1st Qu.:  0.0   2012-10-02:  288   1st Qu.: 589  
##  Median :  0.0   2012-10-03:  288   Median :1178  
##  Mean   : 37.4   2012-10-04:  288   Mean   :1178  
##  3rd Qu.: 12.0   2012-10-05:  288   3rd Qu.:1766  
##  Max.   :806.0   2012-10-06:  288   Max.   :2355  
##  NA's   :2304    (Other)   :15840
All of the NA's are in the steps variable. There are 2304 NA's.

Strategy for filling in all of the missing values in the dataset

The following strategy is chosen: for any NA is the step variable, the mean (of steps) of the corresponding interval is taken as the replacing value.

The 'mn_int' contains the mean for each single interval calculated over the 61 days. The right value coming from 'mn_int' is going to be used to replace the NA at the same interval.

echo = TRUE
activity2 <- activity  # creation of the dataset that will have no more NAs
for (i in 1:nrow(activity)){
    if(is.na(activity$steps[i])){
        activity2$steps[i]<- mn_int[[as.character(activity[i, "interval"])]]
    }
}
Below is a histogram of the total number of steps taken each day. The mean and median total number of steps taken per day are reported.

echo = TRUE
su2 <- tapply(activity2$steps, activity2$date, sum, na.rm=T)
hist(su2, xlab = "sum of steps per day", main = "histogram of steps per day")
plot of chunk unnamed-chunk-10

mean_su2 <- round(mean(su2))
median_su2 <- round(median(su2))
The new values are :

echo = TRUE
print(c("The mean is",mean_su2))
## [1] "The mean is" "10766"
print(c("The median is",median_su2))
## [1] "The median is" "10766"
In order to compare the new values with the “old” values:

echo = TRUE
df_summary <- rbind(df_summary, data.frame(mean = c(mean_su, mean_su2), median = c(median_su, median_su2)))
rownames(df_summary) <- c("with NA's", "without NA's")
print(df_summary)
##               mean median
## with NA's     9354  10395
## without NA's 10766  10766
For comparison with NA's and without (see earlier):

echo = TRUE
summary(activity2)
##      steps               date          interval   
##  Min.   :  0.0   2012-10-01:  288   Min.   :   0  
##  1st Qu.:  0.0   2012-10-02:  288   1st Qu.: 589  
##  Median :  0.0   2012-10-03:  288   Median :1178  
##  Mean   : 37.4   2012-10-04:  288   Mean   :1178  
##  3rd Qu.: 27.0   2012-10-05:  288   3rd Qu.:1766  
##  Max.   :806.0   2012-10-06:  288   Max.   :2355  
##                  (Other)   :15840
It confirms there is no more NAs in the steps variable.


